name: Deploy Files

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy Files"
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Deploy Files"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "ftp" #221 for SFTP
          remote-port: 21
          remote-host: "f34-preview.awardspace.net"
          remote-user: "4431943_admin" # in docs with square brackets
          remote-password: ${{ secrets.FTP_PASSWORD }}
          remote-path: "/"
          sync: "full" # total copy 
