name: Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy Files
        uses: milanmk/actions-file-deployer@master
        with:
          remote-host: "f34-preview.awardspace.net"
          remote-port: 21
          remote-protocol: "ftp"
          remote-user: 4431943
          ssh-private-key: ${{ secrets.FTP_PASSWORD }}
          remote-path: "/home/www" 
