name: Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: joutvhu/ftp-transfer@v1
        with:
          host: localhost
          port: 21
          username: joutvhu
          password: ${{ secrets.FTP_PASSWORD }}
          commands: |
            put ./build ./build.new
            rename ./build ./build.old
            rename ./build.new ./build
            delete ./build.old

